// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/maistra/istio-operator/pkg/clientset/versioned/typed/maistra/v2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMaistraV2 struct {
	*testing.Fake
}

func (c *FakeMaistraV2) ServiceMeshControlPlanes(namespace string) v2.ServiceMeshControlPlaneInterface {
	return &FakeServiceMeshControlPlanes{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMaistraV2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
