apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-huszty
  namespace: external-istiod
  labels:
    istio.io/rev: default
    install.operator.istio.io/owning-resource: unknown
    operator.istio.io/component: "Pilot"
    release: istio
data:
  meshNetworks: |-
    networks: {}
  mesh: |-
    defaultConfig:
      discoveryAddress: external-opneshift-72287d3323ba21ca6bea483947a1068a-0002.eu-de.containers.appdomain.cloud:15443
      meshId: mesh1
    enablePrometheusMerge: true
    rootNamespace: external-istiod
    trustDomain: cluster.local